/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package food.city.system.view;

import food.city.system.controller.EmployeePaysheetController;
import food.city.system.dto.EmployeeDTO;
import food.city.system.dto.PaysheetDTO;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Avishka
 */
public class EmployeePaysheet extends javax.swing.JFrame {

    /**
     * Creates new form EmployeePaysheet
     */
    
    private EmployeePaysheetController employeePaysheetController;
    private Main main;
    
    public EmployeePaysheet(Main main) {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        this.main = main;
        main.setVisible(false);
        
        this.employeePaysheetController = new EmployeePaysheetController();
        
        employeeIdtxt.requestFocus();
        addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                main.setVisible(true);
                e.getWindow().dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLabel = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        employeeIdtxt = new javax.swing.JTextField();
        employeeNametxt = new javax.swing.JTextField();
        jlabel1 = new javax.swing.JLabel();
        jlabel2 = new javax.swing.JLabel();
        fixedSalarytxt = new javax.swing.JTextField();
        otRatetxt = new javax.swing.JTextField();
        jlabel3 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();
        otHourstxt = new javax.swing.JTextField();
        totalOTAmount = new javax.swing.JTextField();
        jlabel5 = new javax.swing.JLabel();
        jlabel6 = new javax.swing.JLabel();
        totalSlaryTxt = new javax.swing.JTextField();
        savePaysheetBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainLabel.setFont(new java.awt.Font("Droid Sans", 1, 24)); // NOI18N
        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel.setText("Employee Paysheet");

        jlabel.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N
        jlabel.setText("Employee ID : ");

        employeeIdtxt.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        employeeIdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeIdtxtActionPerformed(evt);
            }
        });

        employeeNametxt.setEditable(false);
        employeeNametxt.setBackground(new java.awt.Color(255, 255, 255));
        employeeNametxt.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        employeeNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeNametxtActionPerformed(evt);
            }
        });

        jlabel1.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N
        jlabel1.setText("Employee Name : ");

        jlabel2.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N
        jlabel2.setText("Fixed Salary : ");

        fixedSalarytxt.setEditable(false);
        fixedSalarytxt.setBackground(new java.awt.Color(255, 255, 255));
        fixedSalarytxt.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        fixedSalarytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixedSalarytxtActionPerformed(evt);
            }
        });

        otRatetxt.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        otRatetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otRatetxtActionPerformed(evt);
            }
        });

        jlabel3.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N
        jlabel3.setText("OT Rate(per hour) : ");

        jlabel4.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N
        jlabel4.setText("Total OT hours: ");

        otHourstxt.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        otHourstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otHourstxtActionPerformed(evt);
            }
        });

        totalOTAmount.setEditable(false);
        totalOTAmount.setBackground(new java.awt.Color(255, 255, 255));
        totalOTAmount.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        totalOTAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalOTAmountActionPerformed(evt);
            }
        });

        jlabel5.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N
        jlabel5.setText("Total OT Amount: ");

        jlabel6.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N
        jlabel6.setText("Total salary: ");

        totalSlaryTxt.setEditable(false);
        totalSlaryTxt.setBackground(new java.awt.Color(255, 255, 255));
        totalSlaryTxt.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        totalSlaryTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalSlaryTxtActionPerformed(evt);
            }
        });

        savePaysheetBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        savePaysheetBtn.setText("Save");
        savePaysheetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePaysheetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(employeeIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(employeeNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(otRatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(otHourstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalOTAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(savePaysheetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(totalSlaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fixedSalarytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addComponent(mainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel)
                    .addComponent(employeeIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel1)
                    .addComponent(employeeNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel2)
                    .addComponent(fixedSalarytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel3)
                    .addComponent(otRatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel4)
                    .addComponent(otHourstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel5)
                    .addComponent(totalOTAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel6)
                    .addComponent(totalSlaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(savePaysheetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeIdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeIdtxtActionPerformed
        try {
            String Eid = employeeIdtxt.getText();
            EmployeeDTO employeeDTO = employeePaysheetController.getEmployee(Eid);

            if (employeeDTO==null) {
                JOptionPane.showMessageDialog(this, "Insert valid employee ID");
                return;
            }
            
            if (employeePaysheetController.searchEmployee(Eid)) {
                JOptionPane.showMessageDialog(this, "Paysheet has already created for this employee");
                return;
            }
            
            employeeNametxt.setText(employeeDTO.getName());
            fixedSalarytxt.setText(employeeDTO.getSalary()+"");
            totalSlaryTxt.setText(employeeDTO.getSalary()+"");
            otRatetxt.requestFocus();
        } catch (Exception ex) {
            Logger.getLogger(EmployeePaysheet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_employeeIdtxtActionPerformed

    private void employeeNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeNametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeNametxtActionPerformed

    private void fixedSalarytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixedSalarytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fixedSalarytxtActionPerformed

    private void otRatetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otRatetxtActionPerformed
        otHourstxt.requestFocus();
    }//GEN-LAST:event_otRatetxtActionPerformed

    private void otHourstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otHourstxtActionPerformed
        savePaysheetBtn.requestFocus();
        float otRate = Float.parseFloat(otRatetxt.getText());
        float otHours = Float.parseFloat(otHourstxt.getText());
        totalOTAmount.setText(otRate*otHours+"");
        float fixedSal = Float.parseFloat(fixedSalarytxt.getText());
        float otAmount = Float.parseFloat(totalOTAmount.getText());
        totalSlaryTxt.setText((otAmount + fixedSal)+"");
    }//GEN-LAST:event_otHourstxtActionPerformed

    private void totalOTAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalOTAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalOTAmountActionPerformed

    private void totalSlaryTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalSlaryTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalSlaryTxtActionPerformed

    private void savePaysheetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePaysheetBtnActionPerformed
        
        String Eid = employeeIdtxt.getText();
        if (Eid.equals("")||otRatetxt.getText().equals("")||otHourstxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Fill empty fields");
            return;
        }
        float otRate = Float.parseFloat(otRatetxt.getText());
        float otHours = Float.parseFloat(otHourstxt.getText());
        float fixedSal = Float.parseFloat(fixedSalarytxt.getText());
        float otAmount = Float.parseFloat(totalOTAmount.getText());
        float totalSalary = fixedSal+otAmount;
        String date = LocalDate.now().toString();
        
        
        PaysheetDTO paysheetDTO = new PaysheetDTO(Eid, fixedSal, otRate, otHours, otAmount, totalSalary, date);
        
        try {
            boolean success = employeePaysheetController.savePaysheet(paysheetDTO);
            if (success) {
                JOptionPane.showMessageDialog(this, "Paysheet Successfully added");
            }else{
                JOptionPane.showMessageDialog(this, "Paysheet already created.");
            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeePaysheet.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        clearFields();
        employeeIdtxt.requestFocus();;
    }//GEN-LAST:event_savePaysheetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeePaysheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeePaysheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeePaysheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeePaysheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField employeeIdtxt;
    private javax.swing.JTextField employeeNametxt;
    private javax.swing.JTextField fixedSalarytxt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JLabel jlabel6;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JTextField otHourstxt;
    private javax.swing.JTextField otRatetxt;
    private javax.swing.JButton savePaysheetBtn;
    private javax.swing.JTextField totalOTAmount;
    private javax.swing.JTextField totalSlaryTxt;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        employeeIdtxt.setText("");
        employeeNametxt.setText("");
        fixedSalarytxt.setText("");
        otRatetxt.setText("");
        otHourstxt.setText("");
        totalOTAmount.setText("");
        totalSlaryTxt.setText("");
    }
}
