/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package food.city.system.view;

import food.city.system.controller.DailyInfoController;
import food.city.system.dto.ItemDTO;
import food.city.system.dto.OrderDetailDTO;
import food.city.system.dto.SupplyDeteilDTO;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.text.DateFormatSymbols;
import java.time.LocalDate;
import java.time.YearMonth;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Avishka
 */
public class PreviousDailyInfo extends javax.swing.JFrame {

    /**
     * Creates new form PreviousDailyInfo
     */
    
    private DailyInfoController dailyInfoController;
    private float totRevenue = 0;
    private float totSupply = 0;
    private float tot = 0;
    private String date;
    private ArrayList<OrderDetailDTO> ordersDetails;
    private ArrayList<SupplyDeteilDTO> suppliersItemsDetails;
    private boolean showAll = false;
    private Main main;
    
    private int START_YEAR = 2020;
    private String[] monthList;
    private int comboMonth=1;
    private int comboYear=2020;
    private int comboDay=1;
    
    public PreviousDailyInfo(Main main) {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        this.main = main;
        main.setVisible(false);
        
        String today = LocalDate.now().toString();
        int currYear = Integer.parseInt(today.substring(0, 4));
        monthList = new DateFormatSymbols().getMonths();
        
        for (int i = START_YEAR; i <= currYear; i++) {
            yearComboBox.addItem(currYear+"");
        }

        for (String string : monthList) {
            if (string.equals("")) {
                continue;
            }
            monthComboBox.addItem(string);
        }
        
        setDaysComboBox(31);
        if (comboMonth<10 && comboDay<10) {
            date = comboYear+"-0"+comboMonth+"-0"+comboDay;
        }else if (comboMonth<10) {
            date = comboYear+"-"+comboMonth+"-"+comboDay;
        }else if (comboDay<10) {
            date = comboYear+"-"+comboMonth+"-0"+comboDay;
        }else{
            date = comboYear+"-"+comboMonth+"-"+comboDay;
        }
        this.dailyInfoController = new DailyInfoController();
        

        addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                main.setVisible(true);
                e.getWindow().dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        SupplierDetailTbl = new javax.swing.JTable();
        mainLabel1 = new javax.swing.JLabel();
        mainLabel2 = new javax.swing.JLabel();
        ShowAllSupplyItemsbtn = new javax.swing.JButton();
        mainLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        OrderItemsTbl = new javax.swing.JTable();
        totGoodExpencetxt = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        SupplyItemsTbl = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        OrderDetailTbl = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        ShowAllOrderItemsbtn = new javax.swing.JButton();
        grossProfitTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        totRevenuetxt = new javax.swing.JTextField();
        jlabel = new javax.swing.JLabel();
        yearComboBox = new javax.swing.JComboBox<>();
        monthComboBox = new javax.swing.JComboBox<>();
        dayComboBox = new javax.swing.JComboBox<>();
        searchbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainLabel.setFont(new java.awt.Font("Droid Sans", 1, 24)); // NOI18N
        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel.setText("Daily Information History");

        SupplierDetailTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Total Bill"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(SupplierDetailTbl);

        mainLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        mainLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel1.setText("Order Information");

        mainLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        mainLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel2.setText("Supply Information");

        ShowAllSupplyItemsbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ShowAllSupplyItemsbtn.setText("Show All");
        ShowAllSupplyItemsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAllSupplyItemsbtnActionPerformed(evt);
            }
        });

        mainLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        mainLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel3.setText("Daily Profit Information");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Total Expense for Goods :");

        OrderItemsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(OrderItemsTbl);

        totGoodExpencetxt.setEditable(false);
        totGoodExpencetxt.setBackground(new java.awt.Color(255, 255, 255));
        totGoodExpencetxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totGoodExpencetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totGoodExpencetxtActionPerformed(evt);
            }
        });

        SupplyItemsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(SupplyItemsTbl);

        OrderDetailTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Customer ID", "Total Bill"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(OrderDetailTbl);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("GROSS PROFIT :");

        ShowAllOrderItemsbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ShowAllOrderItemsbtn.setText("Show All");
        ShowAllOrderItemsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAllOrderItemsbtnActionPerformed(evt);
            }
        });

        grossProfitTxt.setEditable(false);
        grossProfitTxt.setBackground(new java.awt.Color(255, 255, 255));
        grossProfitTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        grossProfitTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grossProfitTxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Total Revenue :");

        totRevenuetxt.setEditable(false);
        totRevenuetxt.setBackground(new java.awt.Color(255, 255, 255));
        totRevenuetxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totRevenuetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totRevenuetxtActionPerformed(evt);
            }
        });

        jlabel.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N
        jlabel.setText("Date : ");

        yearComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearComboBoxActionPerformed(evt);
            }
        });

        monthComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        monthComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthComboBoxActionPerformed(evt);
            }
        });

        dayComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dayComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayComboBoxActionPerformed(evt);
            }
        });

        searchbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(ShowAllOrderItemsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(335, 335, 335)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totRevenuetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(grossProfitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(mainLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(ShowAllSupplyItemsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(totGoodExpencetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel)
                    .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbtn))
                .addGap(18, 18, 18)
                .addComponent(mainLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowAllOrderItemsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(totRevenuetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowAllSupplyItemsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(totGoodExpencetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(grossProfitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(815, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowAllSupplyItemsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAllSupplyItemsbtnActionPerformed
        showAllSuppliersToday(date);
    }//GEN-LAST:event_ShowAllSupplyItemsbtnActionPerformed

    private void totGoodExpencetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totGoodExpencetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totGoodExpencetxtActionPerformed

    private void ShowAllOrderItemsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAllOrderItemsbtnActionPerformed
        showAllOdersToday(date);

    }//GEN-LAST:event_ShowAllOrderItemsbtnActionPerformed

    private void grossProfitTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grossProfitTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grossProfitTxtActionPerformed

    private void totRevenuetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totRevenuetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totRevenuetxtActionPerformed

    private void yearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboBoxActionPerformed
        comboYear = Integer.parseInt((String) yearComboBox.getSelectedItem());
        YearMonth yearMonthObject = YearMonth.of(comboYear, comboMonth);
        int daysInMonth = yearMonthObject.lengthOfMonth();
        setDaysComboBox(daysInMonth);
    }//GEN-LAST:event_yearComboBoxActionPerformed

    private void monthComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthComboBoxActionPerformed
        comboMonth = monthComboBox.getSelectedIndex()+1;
        YearMonth yearMonthObject = YearMonth.of(comboYear, comboMonth);
        int daysInMonth = yearMonthObject.lengthOfMonth();
        setDaysComboBox(daysInMonth);
    }//GEN-LAST:event_monthComboBoxActionPerformed

    private void dayComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayComboBoxActionPerformed

    }//GEN-LAST:event_dayComboBoxActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        showAll = false;
        totRevenue = 0;
        totSupply = 0;
        tot = 0;
        totRevenuetxt.setText("0.0");
        totGoodExpencetxt.setText("0.0");
        grossProfitTxt.setText("0.0");
        if (dayComboBox.getSelectedItem()!=null) {
            comboDay = Integer.parseInt((String) dayComboBox.getSelectedItem());
        }
        
        if (comboMonth<10 && comboDay<10) {
            date = comboYear+"-0"+comboMonth+"-0"+comboDay;
        }else if (comboMonth<10) {
            date = comboYear+"-"+comboMonth+"-"+comboDay;
        }else if (comboDay<10) {
            date = comboYear+"-"+comboMonth+"-0"+comboDay;
        }else{
            date = comboYear+"-"+comboMonth+"-"+comboDay;
        }
        
        
        try {
            this.ordersDetails = dailyInfoController.getAllOrdersToday(date);
        } catch (SQLException ex) {
            Logger.getLogger(DailyInfo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DailyInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        showAllOdersToday(date);
        
        OrderDetailTbl.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {

                if (OrderDetailTbl.getSelectedRow() == -1) {
                    return;
                }

                String Oid = (String) OrderDetailTbl.getValueAt(OrderDetailTbl.getSelectedRow(), 0);
                for (OrderDetailDTO ordersDetail : ordersDetails) {
                    if (ordersDetail.getOid().equals(Oid)) {
                        DefaultTableModel dtm = (DefaultTableModel) OrderItemsTbl.getModel();
                        dtm.setRowCount(0);
                        showOderItems(ordersDetail.getItemList());
                    }
                }
            }
        });
        
        try {
            this.suppliersItemsDetails = dailyInfoController.getAllSuppliersToday(date);
        } catch (SQLException ex) {
            Logger.getLogger(DailyInfo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DailyInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        showAllSuppliersToday(date);
        showAll = true;
        
        SupplierDetailTbl.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {

                if (SupplierDetailTbl.getSelectedRow() == -1) {
                    return;
                }

                String Sid = (String) SupplierDetailTbl.getValueAt(SupplierDetailTbl.getSelectedRow(), 0);
                for (SupplyDeteilDTO supplyDeteilDTO : suppliersItemsDetails) {
                    if (supplyDeteilDTO.getSid().equals(Sid)) {
                        DefaultTableModel dtm = (DefaultTableModel) SupplyItemsTbl.getModel();
                        dtm.setRowCount(0);
                        showSupplierItems(supplyDeteilDTO.getItemList());
                    }
                }
            }
        });
        showProfitInfoToday(date);
    }//GEN-LAST:event_searchbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreviousDailyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreviousDailyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreviousDailyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreviousDailyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OrderDetailTbl;
    private javax.swing.JTable OrderItemsTbl;
    private javax.swing.JButton ShowAllOrderItemsbtn;
    private javax.swing.JButton ShowAllSupplyItemsbtn;
    private javax.swing.JTable SupplierDetailTbl;
    private javax.swing.JTable SupplyItemsTbl;
    private javax.swing.JComboBox<String> dayComboBox;
    private javax.swing.JTextField grossProfitTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel mainLabel1;
    private javax.swing.JLabel mainLabel2;
    private javax.swing.JLabel mainLabel3;
    private javax.swing.JComboBox<String> monthComboBox;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField totGoodExpencetxt;
    private javax.swing.JTextField totRevenuetxt;
    private javax.swing.JComboBox<String> yearComboBox;
    // End of variables declaration//GEN-END:variables
    private void showAllOdersToday(String today) {
        DefaultTableModel dtm=(DefaultTableModel) OrderDetailTbl.getModel();
        dtm.setRowCount(0);
        DefaultTableModel dtm1=(DefaultTableModel) OrderItemsTbl.getModel();
        dtm1.setRowCount(0);
        for (OrderDetailDTO orderDetails : ordersDetails) {
            Object[] rowData={orderDetails.getOid(),orderDetails.getCid(),orderDetails.getTotal()};
            dtm.addRow(rowData);
            if (showAll==false) {
                totRevenue = totRevenue + orderDetails.getTotal();
            }
            showOderItems(orderDetails.getItemList());
        }
        totRevenuetxt.setText(totRevenue+"");
        
    }

    private void showOderItems(ArrayList<ItemDTO> orderItems) {
        for (ItemDTO item : orderItems) {
            Object[] rowData={item.getIid(),item.getSellingPrice(),item.getNoOfItems()};
            DefaultTableModel dtm=(DefaultTableModel) OrderItemsTbl.getModel();
            dtm.addRow(rowData);
        }
    }

    private void showAllSuppliersToday(String today){
        DefaultTableModel dtm=(DefaultTableModel) SupplierDetailTbl.getModel();
        dtm.setRowCount(0);
        DefaultTableModel dtm1=(DefaultTableModel) SupplyItemsTbl.getModel();
        dtm1.setRowCount(0);
        for (SupplyDeteilDTO supplierItemsDetail : suppliersItemsDetails) {
            Object[] rowData={supplierItemsDetail.getSid(),supplierItemsDetail.getTotal()};
            dtm.addRow(rowData);
            if (showAll==false) {
                totSupply = totSupply + supplierItemsDetail.getTotal();
            }
            showSupplierItems(supplierItemsDetail.getItemList());
            totGoodExpencetxt.setText(totSupply+"");
        }
    }

    private void showSupplierItems(ArrayList<ItemDTO> items) {
        for (ItemDTO item : items) {
            Object[] rowData={item.getIid(),item.getBuyingPrice(),item.getNoOfItems()};
            DefaultTableModel dtm=(DefaultTableModel) SupplyItemsTbl.getModel();
            dtm.addRow(rowData);
        }
    }

    private void showProfitInfoToday(String today) {
        grossProfitTxt.setText((totRevenue-totSupply)+"");
    }
    
    private void setDaysComboBox(int i) {
        dayComboBox.removeAllItems();
        for (int j = 1; j <= i; j++) {
            dayComboBox.addItem(j+"");
        }
    }
}
